### ISSUE TITLE
Review: 01

### ISSUE THREAD

**Issue by justin-mar** [environment-overflow/E-Impact#12]
## Overview

The focus for this code review will be centered around the Dashboard and Landing pages and the BaseCollection.
Please pay attention too:
* Javascript issues
* React components

## Review Branch

[review-01](https://github.com/environment-overflow/E-Impact/tree/review-01)

## Files to review

* [Dashboard.jsx](https://github.com/environment-overflow/E-Impact/blob/main/app/imports/ui/pages/Dashboard.jsx)
* [Landing.jsx](https://github.com/environment-overflow/E-Impact/blob/main/app/imports/ui/pages/Landing.jsx)
* [BaseCollection.js](https://github.com/environment-overflow/E-Impact/blob/main/app/imports/api/base/BaseCollection.js)

## Checklists

* [Architecture](https://github.com/environment-overflow/E-Impact/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/environment-overflow/E-Impact/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/environment-overflow/E-Impact/blob/main/checklists/js-checklist.md)
* [Meteor](https://github.com/environment-overflow/E-Impact/blob/main/checklists/meteor-checklist.md)
* [React](https://github.com/environment-overflow/E-Impact/blob/main/checklists/react-checklist.md)
* [Testing](https://github.com/environment-overflow/E-Impact/blob/main/checklists/testing-checklist.md)

## Due date

Tuesday, Feb. 9 12:00pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by Rexter-DS** [comment]
Dashboard.jsx

Design Checklist
- Could export graphs to be reusable code maybe

Landing.jsx

React Checklist
- Landing should be stateless so it should be function

BaseCollection.js

JS Checklist
- Avoid using underscore functions

**Comment by tiffanywilliams** [comment]
Dashboard
----------

Line 86: semi-colon where it shouldn't be



LandingNavBar
-------------
React-09: Class NavBar could be a function.

**Comment by jcamarao** [comment]
Dashboard.jsx
---------------------
REACT-06: Define constants in withTracker()
REACT-07: don't retrieve colection data inside render()
Didn't do testing?

Landing.jsx
---------------------
REACT-09: Prefer functions vs. classes for stateless components
Design-05: Ensure comments are appropriate
didn't do testing?

BaseCollections.jsx
----------------------
Looks good

**Comment by nicholasmp** [comment]
Design-04
	BaseCollections has a large amount of commenting, unsure if it should or shouldn’t be deleted. 
React-09
	Landing page is a stateless component and can be a function instead of a class. 
No testing…

**Comment by wongk711** [comment]
wrap base collections in a class

**Comment by cammoore** [comment]
Dashboard.jsx
Use function not class.
ESLint new line at end of file.

**Comment by justin-mar** [comment]
Dashboard.jsx:
JS-08: Avoid unnecessary /** (line 6)
REACT-09 Use functions

LandingNavBar:
REACT-09 Use functions

**Comment by lcaraang** [comment]
REACT-09: Prefer functions vs. classes for stateless components.

**Comment by jklaulau** [comment]
Dashboard.jsx
React-06 Define constants in withTracker()

Landing.jsx
React-09 Use functions
