### ISSUE TITLE
Review: 02

### ISSUE THREAD

**Issue by tiffanywilliams** [environment-overflow/E-Impact#40]
## Overview

The focus for this code review will be centered around the Dashboard and Landing pages and the BaseCollection.
Please pay attention too:
* Javascript issues
* React components

## Review Branch

[review-02](https://github.com/environment-overflow/E-Impact/tree/review-02)

## Files to review

* [QuickAccess.jsx](https://github.com/environment-overflow/E-Impact/blob/main/app/imports/ui/pages/QuickAccess.jsx)
* [Daily.jsx](https://github.com/environment-overflow/E-Impact/blob/main/app/imports/ui/pages/Daily.jsx)

## Checklists

* [Architecture](https://github.com/environment-overflow/E-Impact/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/environment-overflow/E-Impact/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/environment-overflow/E-Impact/blob/main/checklists/js-checklist.md)
* [Meteor](https://github.com/environment-overflow/E-Impact/blob/main/checklists/meteor-checklist.md)
* [React](https://github.com/environment-overflow/E-Impact/blob/main/checklists/react-checklist.md)
* [Testing](https://github.com/environment-overflow/E-Impact/blob/main/checklists/testing-checklist.md)

## Due date

Tuesday, March 2, 12:00 pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by Rexter-DS** [comment]
Daily.jsx
- use functions over classes

**Comment by jcamarao** [comment]
Daily.jsx
----------------
REACT-09: Prefer functions vs. classes for stateless components


QuickAcess.jsx
----------------
REACT-06: Define constants in withTracker() (I think idk)
DESIGN-04: Eliminate large comment blocks (But I know they're just notes to help guide you, so maybe not an issue)

**Comment by tiffanywilliams** [comment]
QuickCheck.jsx
----------------
Design-03: Lines 110 to 113. Could delete if not in use anymore. 

JS-01: Could rename parameters (x, y, e) to be more specific/descriptive. 


Daily.jsx
-----------------
React-09: Stateless, could turn it into a function.

**Comment by wongk711** [comment]
only found repeats from above:
Daily:
- arrow function instead of class

Quick Access:
- arrow function instead of "function" 
- wrap const's in  const withTracker

**Comment by lcaraang** [comment]
Daily 
REACT-09: Prefer functions vs. classes for stateless components.

QuickAccess
L110-113: Design-03: Eliminate dead code.

**Comment by jklaulau** [comment]
Daily.jsx
Use functions instead of classes

QuickAccess
Remove large comment blocks

**Comment by nicholasmp** [comment]
**QuickAccess.jsx**
Design-04: Lines 10-16 are comments that should be deleted.
Design-05: Lines 10-16 comments are unnecessary.
Design-07: Additional comments could be added to explain some features.

**Daily.jsx**
React-03: SideBar import renamed to SideBarVisible.
React-09: Function can be used instead of a class.

**Comment by justin-mar** [comment]
QuickAccess.jsx:
        Lines 10-16, I think the comment block needs to be broken up more into describing the functions and things to be added
        For the subsequent functions, I think comments should be added to explain them more
	Lines 110-113, are the comments necessary?
	
Daily.jsx:
	Maybe add comments explaining what each part is

**Comment by cammoore** [comment]
Javascript: L39 The value === '4' is confusing until you get to the
select on L85. Could we use different values like 'bike', 'bus', etc.? 

React: L53 Why aren't we using semantic-ui-react components?

Daily.jsx

React-09: L5 Why are we using a class?

Javascript/React: L13 - 61 Hard coded values. Do we have a plan for
getting these values from a collection?
