### ISSUE TITLE
Review: 3

### ISSUE THREAD

**Issue by jcamarao** [environment-overflow/E-Impact#48]
## Overview

The focus for this code review will be centered around the SideBar and Map components.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-003

## Files to review

[SideBar.jsx](https://github.com/environment-overflow/E-Impact/blob/main/app/imports/ui/components/SideBar.jsx)
[Map.jsx](https://github.com/environment-overflow/E-Impact/blob/main/app/imports/ui/components/Map.jsx)

## Checklists

* [Architecture](https://github.com/environment-overflow/E-Impact/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/environment-overflow/E-Impact/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/environment-overflow/E-Impact/blob/main/checklists/js-checklist.md)
* [Meteor](https://github.com/environment-overflow/E-Impact/blob/main/checklists/meteor-checklist.md)
* [React](https://github.com/environment-overflow/E-Impact/blob/main/checklists/react-checklist.md)
* [Testing](https://github.com/environment-overflow/E-Impact/blob/main/checklists/testing-checklist.md)

## Due date

Tueday, March 9 12:00 PM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by jcamarao** [comment]
SideBar.jsx
----------------
REACT-09: Prefer functions vs. classes for stateless components
Design-03: Eliminate dead code? (Take out the console.log comment)


Map.jsx
----------------
REACT-06: Define constants in withTracker()
REACT-09: Prefer functions vs. classes for stateless components

**Comment by Rexter-DS** [comment]
Sidebar.jsx
- eliminate unused code
- use withTracker to get the current user

Map.jsx
- destructure props
- don't rename export defaults?
- use functions over class

**Comment by tiffanywilliams** [comment]
SideBar.jsx
-----------------
Design-03: Delete commented out console.log on line 8.

Export SidebarVisible, file name is SideBar.jsx



Map.jsx
----------
React-09: Prefer functions vs. classes for stateless components.

**Comment by nicholasmp** [comment]
SideBar.jsx
JS-07: Commented Console.log 

Map.jsx
React-09: Line 9 class MapContainer vs function

**Comment by jklaulau** [comment]
Sidebar.jsx
JS-07: Remove comment (console.log)

Map.jsx
React-06: Define constants with tracker

**Comment by wongk711** [comment]
Sidebar.jsx:
- get rid of commented/unused code
- match export with filename

Map.jsx
- use withTracker for consts

**Comment by cammoore** [comment]
SideBar.jsx

Arch-01, JS-01 name of file and component should match.

L7 Might want another const for the username then we don't need to use
Meteor.user() on L26 and L68.

Map.jsx

REACT-09: L9 prefer functions

Arch-01, JS-01 name of file and component should match.

Meteor: L28 Should get the API KEY from Meteor.settings.

**Comment by justin-mar** [comment]
SideBar.jsx;
	Line 8: Unnecessary comment
	REACT-03: I think the file name, the function, and the export should all have the same name to make it simpler.
	
Map.jsx:
        I think this should be a function rather than a class
