### ISSUE TITLE
Review: 04

### ISSUE THREAD

**Issue by tiffanywilliams** [environment-overflow/E-Impact#63]
## Overview

The focus for this code review will be centered around the SideBar and Map components.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

[review-04](https://github.com/environment-overflow/E-Impact/tree/review-04)

## Files to review

[DashboardContent.jsx](https://github.com/environment-overflow/E-Impact/blob/main/app/imports/ui/components/DashboardContent.jsx)
[Chart.jsx](https://github.com/environment-overflow/E-Impact/blob/main/app/imports/ui/components/Chart.jsx)

## Checklists

* [Architecture](https://github.com/environment-overflow/E-Impact/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/environment-overflow/E-Impact/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/environment-overflow/E-Impact/blob/main/checklists/js-checklist.md)
* [Meteor](https://github.com/environment-overflow/E-Impact/blob/main/checklists/meteor-checklist.md)
* [React](https://github.com/environment-overflow/E-Impact/blob/main/checklists/react-checklist.md)

## Due date

Tueday, March 30 12:00 PM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by jcamarao** [comment]
DashboardContent.jsx
------------------------------
REACT-01: Components should be simple (I think, maybe?)
REACT-06: Define constacts in withTracker()

**Comment by tiffanywilliams** [comment]
Chart.jsx
-------------
ESLINT-01: Eslint error on line 17, curly spacing. 


DashboardContent.jsx
----------------------
REACT-01: Components should be simple. Maybe break DashboardContent into smaller subcomponents?

**Comment by Rexter-DS** [comment]
DashboardContent.jsx
- break up content component into sub component for simpler to read code

Chart.jsx
- Eslint error; should have a spacing before curly brace

**Comment by nicholasmp** [comment]
**DashboardContent.jsx**
ESLINT-02: Plotly properties are highlighted as spelling errors

**Comment by lcaraang** [comment]
DashboardContent.jsx
L27 - 28: If I log a trip using a secondary car with a different mpg, it’ll still calculate with profile’s mpg? 
Where does it get the autoMPG when it's a new user with no trips? Page will throw error?

**Comment by justin-mar** [comment]
DashboardContent.jsx
	Comment what each section does to make it easier to understand
        Break it up into smaller sections for easier readability
	
Chart.jsx
        Eslint error

**Comment by cammoore** [comment]
DashboardContent.jsx

L46, 48 Might want a const defined somewhere for the 19.6 value
L59, 60 Might want a const for the 48 lbs of CO2.
L130, 156, 182, 208 create a style const so we can adjust all the
cards
L218, 238, etc Create style consts for the different components so we
have one place to edit them.

Chart.jsx

L17 do we want to pass in the style with a default value?
