### ISSUE TITLE
Review: 05

### ISSUE THREAD

**Issue by Rexter-DS** [environment-overflow/E-Impact#76]
## Overview

The focus for this code review will be centered around the What If page.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

[review-05](https://github.com/environment-overflow/E-Impact/tree/review-05)

## Files to review

* [ChooseScenario.jsx](https://github.com/environment-overflow/E-Impact/blob/main/app/imports/ui/components/ChoseScenario.jsx)
* [WhatIfContent.jsx](https://github.com/environment-overflow/E-Impact/blob/main/app/imports/ui/components/WhatIfContent.jsx)

## Checklists

* [Architecture](https://github.com/environment-overflow/E-Impact/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/environment-overflow/E-Impact/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/environment-overflow/E-Impact/blob/main/checklists/js-checklist.md)
* [Meteor](https://github.com/environment-overflow/E-Impact/blob/main/checklists/meteor-checklist.md)
* [React](https://github.com/environment-overflow/E-Impact/blob/main/checklists/react-checklist.md)

## Due date

April 13 at 12:00PM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by jcamarao** [comment]
WhatIfContent.jsx
---------------------
Design-01: Reduce code duplication by creating one style const
REACT-06: consts in withTracker()
Arch-01: Files use camel case (idk I think)

ChooseScenario.jsx
---------------------
ESLINT-01: ESLint errors appear
REACT-06: consts in withTracker()
Arch-01: Files use camel case (idk I think)

**Comment by tiffanywilliams** [comment]
ChoseScenario.jsx
-----------------
Design-01: Could reduce some duplicated code (lines 42-56 & lines 66-80).
ESLINT-01: ESLint errors.

**Comment by cammoore** [comment]
## ChooseScenario.jsx

L28, 34, 39 should this be const? It doesn't change.

L68 - 77, 86 - 95 Duplicate code can we refactor into a function that
returns a 2 digit string?

## WhatIfContent.jsx

L79 should this be a common function that other components can use?

**Comment by wongk711** [comment]
### what if 
* lots of repeated code can be reduced
* consts in withTracker

### choose Scenario
* more repeated code

**Comment by justin-mar** [comment]
ChooseScenario.jsx:
	Line 23: Doesn't do anything
	Line 67-77 and 85-95: Potential merging to one function to handle dates

WhatIfContent.jsx:
	Design-01: Possible refactor to reduce duplication with DashboardContent.jsx
	Line 17, 20, 251, and 254: Can get rid of

**Comment by nicholasmp** [comment]
**ChoseScenario.jsx**
ESLINT-01: Errors on line 13, 18, 19, 28, 34, and 39 for being defined and never used.
Lines 42-56 and lines 66-80 are duplicates.

**WhatIfContent.jsx**
DESIGN-03: Line 17, 20, 251, 254 are unused lines of code.

**Comment by Rexter-DS** [comment]
ChooseScenario.jsx
- duplicate code

WhatIfContent.jsx
- I added an exported const for calculation stuff (e.g. ghg per gallon (19.6) ) so might want to update

**Comment by lcaraang** [comment]
Design-01: Duplicated code
