### ISSUE TITLE
Review: 06

### ISSUE THREAD

**Issue by justin-mar** [environment-overflow/E-Impact#92]
## Overview

The focus for this code review will be centered around the Daily page.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-006

## Files to review

* [Daily.jsx](https://github.com/environment-overflow/E-Impact/blob/main/app/imports/ui/pages/Daily.jsx)
* [CommunityStats.jsx](https://github.com/environment-overflow/E-Impact/blob/main/app/imports/ui/components/CommunityStats.jsx)

## Checklists

* [Architecture](https://github.com/environment-overflow/E-Impact/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/environment-overflow/E-Impact/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/environment-overflow/E-Impact/blob/main/checklists/js-checklist.md)
* [Meteor](https://github.com/environment-overflow/E-Impact/blob/main/checklists/meteor-checklist.md)
* [React](https://github.com/environment-overflow/E-Impact/blob/main/checklists/react-checklist.md)

## Due date

Day, Month Day Time

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by wongk711** [comment]
* Daily 
  * Duplicate code at top for setting up consts (admin daily i think)
* CommunityStats
  * define consts withTracker?
  *

**Comment by tiffanywilliams** [comment]
Daily.jsx
---------
Duplicate code with AdminDaily.jsx from lines 13-106.

CommunityStats.jsx
-----------------
Design-01: Graph layouts (lines 47-154) could be refactored to reduce duplication. 
React-06: define const trip in withTracker

**Comment by jcamarao** [comment]
Daily.jsx
--------------------
Design-09: Reusable code is exported or made available in the appropriate place (?)
JS-06: Avoid lodash or underscore map, filter, etc.


CommunityStats.jsx
---------------------
REACT-06: Define constants in withTracker()

**Comment by Rexter-DS** [comment]
Daily.jsx
- destructure props

CommunityStats.jsx
- use functions
- destructure props
-

**Comment by justin-mar** [comment]
Daily.jsx:
  * Duplicate code

CommunityStats.jsx:
  *  Use functions over class

**Comment by lcaraang** [comment]
Daily.jsx
Design-09: Ensure reusable code is exported or made available in the appropriate place.

CommunityStats.jsx
REACT-06: Define constants in withTracker().

**Comment by jklaulau** [comment]
Daily.jsx
Design-09: Duplicate code

CommunityStats.jsx
React-06: Define constants in withTracker()

**Comment by cammoore** [comment]
## Daily.jsx

JS-06 Avoid underscore
https://github.com/environment-overflow/E-Impact/blob/11e3dc368f3e769b9687c96d470e3b7d0f09b9b2/app/imports/ui/pages/Daily.jsx#L16 

JS-05 Use arrow functions L31, 40, 49, 53,60

## CommunityStats.jsx

REACT-09 Prefer functions
https://github.com/environment-overflow/E-Impact/blob/11e3dc368f3e769b9687c96d470e3b7d0f09b9b2/app/imports/ui/components/CommunityStats.jsx#L12

JS-04 Use object deconstruction L26 - 34

REACT-06 Define constants in withTracker https://github.com/environment-overflow/E-Impact/blob/11e3dc368f3e769b9687c96d470e3b7d0f09b9b2/app/imports/ui/components/CommunityStats.jsx#L270-L271

**Comment by nicholasmp** [comment]
**Daily.jsx**
JS-06: Line16, Could the underscore filter function be replaced by the default one?

**CommunityStats.jsx**
ESLINT-01: 4 warnings regarding liens 42-45
